module Constant

  EXPORT_PROJECTS = {  
                      project_number: 'Project Id#',
                      name: 'Project Name',
                      company: 'Company Name',
                      project_manager: 'Project Manager',
                      status: 'Status',
                      elimination_reason: 'Elimination Reason',
                      active_date: 'Active Date',
                      contact: 'Contact',
                      business_type: 'Business Type',
                      project_type: 'Project Type',
                      industry_type: 'Industry Type',
                      description: 'Project Description',
                      square_feet_requested: 'Square Feet Requested',
                      square_footage_note: 'Square Footage Notes',
                      #real_estate_requested: 'Real Estate Requested',
                      acres_requested: 'Acres Requested',
                      acreage_note: 'Acreage Notes',
                      new_jobs: 'New Jobs',
                      retained_jobs: 'Retained Jobs',
                      new_jobs_notes: 'New Jobs Notes',
                      wages: 'Wages',
                      wages_notes: 'Wages Notes',
                      net_new_investment: 'Net New Investment',
                      net_new_investment_notes: 'New Investment Notes',
                      considered_location: 'Considered Locations',
                      incentive: 'Incentives',
                      competition: 'Competition',
                      source: 'Source',
                      site_visits: 'Site Visits',
                      site_selector: 'Site Selector',
                      utilize_sites: 'Sites and Building Database Utilized',
                      speculative_building: 'Speculative Building',
                      where_located: 'Located',
                      public_release: 'Public Release',
                      public_release_date: 'Public Release Date',
                      successful_completion_date: 'Completion Date'
                    }

  EXPORT_COMPANIES ={  
                      name: 'Company Name',
                      company_number: 'Company Number',
                      industry_type: 'Industry Type',
                      address_line_1: 'Street Address 1',
                      address_line_2: 'Street Address 2',
                      city: 'City',
                      state: 'State',
                      zip_code: 'Zip Code',
                      country: 'Country',
                      region: 'Region',
                      cell_phone: 'Telephone',
                      fax: 'Fax',
                      website: 'Website',
                      email: 'Email',
                      member_investor: 'Member Investor',
                      notes: 'Company Notes',
                      years_business_located: 'Years Business Located in Community',
                      company_establishment_year: 'Years Company Established in Community',
                      project_type: 'Type of Facility',
                      acreage: 'Acreage',
                      building_size: 'Building Size',
                      number_of: 'Number of Buildings',
                      average_age_of_buildings: 'Average Age of Buildings',
                      room_for_expansion: 'Is there Room for Expansion at this location',
                      owned_or_leased: 'Owned or Leased',
                      lease_expiration_date: 'Lease Expiration Date',
                      owner: 'Property Owner',
                      facility_notes: 'Facility Notes',
                      primary_products_and_services: 'Primary Products',
                      naics_code_1: 'NAICS Code 1',
                      naics_code_2: 'NAICS Code 2',
                      naics_code_3: 'NAICS Code 3',
                      naics_code_4: 'NAICS Code 4',
                      naics_code_5: 'NAICS Code 5',
                      full_time_employees: 'Full-Time Employees',
                      part_time_employees: 'Part-Time Employees',
                      leased_employees: 'Leased Employees',
                      total_employees: 'Total Employees',
                      date_of_total: 'Date of Total',
                      number_of_jobs_added_or_lost_in_past_3_years: 'Number of Jobs Added/Lost in past 3 yrs',
                      number_of_shifts_per_day: 'Number of shifts per day',
                      number_of_days_per_week: 'Number of Days per Week',
                      peak_season: 'Peak Season',
                      average_annual_salary: 'Average Annual Wage/Salary',
                      employment_notes: 'Employment Notes',
                      business_union_represented: 'Business Union Represented',
                      union_notes: 'Union Notes'
                    }

  EXPORT_CONTACTS = {  
                      name: 'Contact Name',
                      organization: 'Organization',
                      title: 'Title',
                      address_line_1: 'Address 1',
                      address_line_2: 'Address 2',
                      city_state_zip: 'City State Zip',
                      phone_number_1: 'Phone 1',
                      phone_number_2: 'Phone 2',
                      cell_phone: 'Cell Phone',
                      fax: 'Fax',
                      email: 'Email',
                      website: 'Website',
                      notes: 'Notes',
                      contact_category: 'Categories',
                      linkedin_url: 'Linkedin Url'
                    }

  GENERAL_MODULES = [
                      { name: 'Home', controller_name: 'dashboard' },
                      { name: 'Tasks', controller_name: 'tasks' },
                      { name: 'Mailbox', controller_name: 'emails' },
                      { name: 'Activities', controller_name: 'activities' },
                      { name: 'Contacts', controller_name: 'contacts' },
                      { name: 'Projects', controller_name: 'projects' },
                      { name: 'Companies', controller_name: 'companies' },
                      { name: 'Sites & Buildings', controller_name: 'sites' },
                      { name: 'Reports', controller_name: 'reports' },
                      { name: 'Files', controller_name: 'files' },
                      { name: 'Data Imports', controller_name: 'imports' },
                      { name: 'Data Exports', controller_name: 'exports' },
                      { name: 'Settings', controller_name: 'manage_users'}
                    ]

  CUSTOM_MODULES = [
                     { name: 'Module 1', controller_name: 'module_one' },
                     { name: 'Module 2', controller_name: 'module_two' },
                     { name: 'Dropbox', controller_name: 'dropboxes', side_bar_enabled: false }
                   ]

  MODULE_ICONS = {
                   dashboard: 'fa fa-home',
                   tasks: 'fa fa-tasks',
                   emails: 'fa fa-envelope',
                   activities: 'fa fa-handshake-o',
                   contacts: 'fa fa-address-book-o',
                   projects: 'fa fa-gears',
                   companies: 'fa fa-building-o',
                   sites: 'material-icons, domain',
                   reports: 'fa fa-file-text-o',
                   files: 'fa fa-files-o',
                   imports: 'fa fa-file-excel-o',
                   exports: 'fa fa-file-excel-o',
                   module_one: 'fa fa-cube',
                   module_two: 'fa fa-cube',
                   dropboxes: 'fa fa-dropbox',
                   manage_users: 'md-settings'
                 }

  SECTIONS = [
               'dashboard', 'tasks', 'emails', 'activities', 'contacts', 'projects',
               'companies', 'sites', 'reports', 'files', 'imports', 'exports',
               'manage_users', 'manage_configurations', 'considered_locations',
               'security_roles', 'project_logs', 'organization_details'
             ]

  EMAIL_TYPES = [
            {name: 'Welcome New Organization', type_id: 1, recipient_roles: 'org'},
            {name: 'Welcome First User', type_id: 2, recipient_roles: 'first_org_admin'},
            {name: 'Reset Password', type_id: 3, recipient_roles: 'all'},
            {name: 'Reset Password Confirmation', type_id: 4, recipient_roles: 'all'},
            {name: 'New Task Creation', type_id: 5, recipient_roles: 'org_users'},
            {name: 'New Task Assigned', type_id: 6, recipient_roles: 'org_users'},
            {name: 'New Tasks Re-Assigned', type_id: 7, recipient_roles: 'org_users'},
            {name: 'New User Invitation', type_id: 8, recipient_roles: 'org_users'},
            {name: 'New User Invite Notification(admins)', type_id: 9, recipient_roles: 'org_admins'},
            {name: 'Welcome New User', type_id: 10, recipient_roles: 'org_users'},
            {name: 'New User Notification(admins)', type_id: 11, recipient_roles: 'org_admins'},
            {name: 'New User Invite Notification(inviter)', type_id: 12, recipient_roles: 'org_admins'},
            {name: 'New User Notification(inviter)', type_id: 13, recipient_roles: 'org_users'},
            {name: 'New User Emails', type_id: 14, recipient_roles: ''},
            {name: 'New User Invitation Emails', type_id: 15, recipient_roles: ''},
            {name: 'New User Welcome Emails', type_id: 16, recipient_roles: ''},
            {name: 'Task Assignment Emails', type_id: 17, recipient_roles: ''},
            {name: 'Reset Password Emails', type_id: 18, recipient_roles: ''},
            {name: 'Other Emails', type_id: 19, recipient_roles: ''}
          ]
end