module Constant

  EXPORT_PROJECTS = {  
                      project_number: 'Project Id#',
                      name: 'Project Name',
                      company: 'Company Name',
                      project_manager: 'Project Manager',
                      status: 'Status',
                      elimination_reason: 'Elimination Reason',
                      active_date: 'Active Date',
                      contact: 'Contact',
                      business_type: 'Business Type',
                      project_type: 'Project Type',
                      industry_type: 'Industry Type',
                      description: 'Project Description',
                      square_feet_requested: 'Square Feet Requested',
                      square_footage_note: 'Square Footage Notes',
                      #real_estate_requested: 'Real Estate Requested',
                      acres_requested: 'Acres Requested',
                      acreage_note: 'Acreage Notes',
                      new_jobs: 'New Jobs',
                      retained_jobs: 'Retained Jobs',
                      new_jobs_notes: 'New Jobs Notes',
                      wages: 'Wages',
                      wages_notes: 'Wages Notes',
                      net_new_investment: 'Net New Investment',
                      net_new_investment_notes: 'New Investment Notes',
                      considered_location: 'Considered Locations',
                      incentive: 'Incentives',
                      competition: 'Competition',
                      source: 'Source',
                      site_visits: 'Site Visits',
                      site_selector: 'Site Selector',
                      utilize_sites: 'Sites and Building Database Utilized',
                      speculative_building: 'Speculative Building',
                      where_located: 'Located',
                      public_release: 'Public Release',
                      public_release_date: 'Public Release Date',
                      successful_completion_date: 'Completion Date'
                    }

  EXPORT_COMPANIES ={  
                      name: 'Company Name',
                      company_number: 'Company Number',
                      industry_type: 'Industry Type',
                      address_line_1: 'Street Address 1',
                      address_line_2: 'Street Address 2',
                      city: 'City',
                      state: 'State',
                      zip_code: 'Zip Code',
                      country: 'Country',
                      region: 'Region',
                      cell_phone: 'Telephone',
                      fax: 'Fax',
                      website: 'Website',
                      email: 'Email',
                      member_investor: 'Member Investor',
                      notes: 'Company Notes',
                      years_business_located: 'Years Business Located in Community',
                      company_establishment_year: 'Years Company Established in Community',
                      project_type: 'Type of Facility',
                      acreage: 'Acreage',
                      building_size: 'Building Size',
                      number_of: 'Number of Buildings',
                      average_age_of_buildings: 'Average Age of Buildings',
                      room_for_expansion: 'Is there Room for Expansion at this location',
                      owned_or_leased: 'Owned or Leased',
                      lease_expiration_date: 'Lease Expiration Date',
                      owner: 'Property Owner',
                      facility_notes: 'Facility Notes',
                      primary_products_and_services: 'Primary Products',
                      naics_code_1: 'NAICS Code 1',
                      naics_code_2: 'NAICS Code 2',
                      naics_code_3: 'NAICS Code 3',
                      naics_code_4: 'NAICS Code 4',
                      naics_code_5: 'NAICS Code 5',
                      full_time_employees: 'Full-Time Employees',
                      part_time_employees: 'Part-Time Employees',
                      leased_employees: 'Leased Employees',
                      total_employees: 'Total Employees',
                      date_of_total: 'Date of Total',
                      number_of_jobs_added_or_lost_in_past_3_years: 'Number of Jobs Added/Lost in past 3 yrs',
                      number_of_shifts_per_day: 'Number of shifts per day',
                      number_of_days_per_week: 'Number of Days per Week',
                      peak_season: 'Peak Season',
                      average_annual_salary: 'Average Annual Wage/Salary',
                      employment_notes: 'Employment Notes',
                      business_union_represented: 'Business Union Represented',
                      union_notes: 'Union Notes'
                    }

  EXPORT_CONTACTS = {  
                      name: 'Contact Name',
                      organization: 'Organization',
                      title: 'Title',
                      address_line_1: 'Address 1',
                      address_line_2: 'Address 2',
                      city_state_zip: 'City State Zip',
                      phone_number_1: 'Phone 1',
                      phone_number_2: 'Phone 2',
                      cell_phone: 'Cell Phone',
                      fax: 'Fax',
                      email: 'Email',
                      website: 'Website',
                      notes: 'Notes',
                      contact_category: 'Categories',
                      linkedin_url: 'Linkedin Url'
                    }
end